version: 0.2

phases:
  build:
    commands:
      - echo "Starting build process..."

artifacts:
  files:
    - '**/*'
  base-directory: 'static_website_sample'
  discard-paths: no

-----------------------------------------------
version: 0.2

phases:
  install:
    commands:
      - echo "Install phase .."
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre build phase ..."
      - sudo yum update -y
      - sudo yum install -y jq       
      
  build:
    commands:
      - echo "Build phase ..."
      - npm install -g sonarqube-scanner
      - sonar-scanner -Dsonar.projectKey=$SONAR_QUBE_PROJECT -Dsonar.host.url=$SONAR_QUBE_URL -Dsonar.login=$SONAR_QUBE_KEY
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - CODEBUILD_BUILD_SUCCEEDING=1
      - if [[ $(jq -r '.projectStatus.status' result.json) == "ERROR" ]]; then CODEBUILD_BUILD_SUCCEEDING=0; fi
      - echo "CODEBUILD_BUILD_SUCCEEDING=${CODEBUILD_BUILD_SUCCEEDING}" >> env.list
  post_build:
    commands:
      - echo "Post build phase ..."